apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      "app.kubernetes.io/name": "{{ name }}"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "{{ name }}"
    spec:
      imagePullSecrets:
      - name: k8s-ecr-login-renew-docker-secret
      containers:
      - name: "{{ name }}"
        image: 456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-plc/plc:{{version}}
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /livez
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: DEBUG
          value: "{{ debug }}"
        - name: ENVIRONMENT
          value: "{{ environment }}"
        - name: NAME
          value: "{{ name }}"
        - name: SPEC
          value: "{{ spec }}"
        - name: KAFKA_BROKERS
          value: "{{ kafka_brokers }}"
        - name: KAFKA_EVENTS_TOPIC
          value: "{{ kafka_events_topic }}"
        - name: KAFKA_MAX_BLOCK_MS
          value: "{{ kafka_max_block_ms }}"
        - name: KAFKA_RETRIES
          value: "{{ kafka_retries }}"
        - name: PLC_TIMEOUT
          value: "{{ plc_timeout }}"
        - name: OTEL_METRICS_EXPORTER
          value: "{{ otel_metrics_exporter }}"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: '{{ otel_exporter_otlp_metrics_endpoint }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_TIMEOUT
          value: '{{ otel_exporter_otlp_metrics_timeout }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: '{{ otel_exporter_otlp_metrics_protocol }}'
        - name: OTEL_EXPORTER_OTLP_METRICS_INSECURE
          value: "{{ otel_exporter_otlp_metrics_insecure }}"
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: KUBERNETES_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace