apiVersion: v1
kind: Service
metadata:
  name: "{{ name }}"
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    "app.kubernetes.io/name": "{{ name }}"