apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: plc.events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days 604800000
    segment.bytes: 134217728 # 128 MB