apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plc-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plc-operator
subjects:
  - kind: ServiceAccount
    name: plc-operator
    namespace: plc