apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plc

commonLabels:
  app.kubernetes.io/name: plc-operator
  app.kubernetes.io/component: controller
  app.kubernetes.io/part-of: plc

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/version: 1.4.0

resources:
  - cluster-role.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
